#!/bin/bash


youtube-dl -o "$2.%(ext)s" --extract-audio --audio-format mp3 --write-all-thumbnails $1
mv "$2.mp3" temp.mp3
ffmpeg -i temp.mp3 -acodec copy  -ss "$3" -to "$4" "$2.mp3";
scp -P 22 "$2.mp3" pi@192.168.5.5:/var/www/html/sound-box/soundBox/sounds/;
scp -P 22 "$2.jpg" pi@192.168.5.5:/var/www/html/sound-box/soundBox/images/;
rm -rf $2.*
rm -rf temp*

echo '    {
      "label": "'$2'",
      "soundFile":  "http://gugue.fr/media/soundBox/sounds/'$2'.mp3",
      "image" : "http://gugue.fr/media/soundBox/images/'$2'.jpg",
      "tags": [ "" ]
    },' ;
